Repository tukcomCD2024/DroidBlossom, pull requests merged in 2024-07, with the labels that each got.

#519 feat : 사용자 수정 기능 구현
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/api/AuthApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/api/AuthApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/data/request/EmailSignInRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/data/request/EmailSignUpRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/UpdateMemberDataDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/reqeust/MemberDetailUpdateRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/reqeust/UpdateMemberDataRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberNotificationSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/SocialType.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/oauth/dto/OAuthAttributes.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/oauth/service/CustomOAuth2UserService.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/service/query/FriendQueryServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
Labels: feat

#526 fix : 알림 서버 deleted_at 추가
  backend/notification/src/main/java/site/timecapsulearchive/notification/entity/Notification.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/global/entity/BaseEntity.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/repository/member/MemberRepository.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/repository/notification/NotificationQueryRepositoryImpl.java
Labels: fix

#525 refact : notification 도메인 이동 #515
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberNotificationSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/NotificationStatus.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/facade/MemberFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/api/NotificationApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/api/NotificationApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/data/dto/MemberNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/data/response/MemberNotificationResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/data/response/MemberNotificationSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/CategoryName.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/Notification.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/NotificationCategory.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/NotificationStatus.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/repository/NotificationQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/repository/NotificationQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/repository/NotificationRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/service/NotificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/CreatedCapsuleSkinNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/FriendAcceptNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/FriendReqNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/FriendsReqNotificationsDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/GroupAcceptNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/GroupInviteNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/NotificationRequestMessage.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/TreasureCaptureNotificationDto.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/NotificationCategoryFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/NotificationFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/notification/NotificationQueryRepositoryTest.java
Labels: refact

#524 feat : 회원 탈퇴 API 추가 #515
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/Capsule.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/capsule/CapsuleRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/image/ImageRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/video/VideoRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleOpenService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/friend_invite/FriendInviteRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/member_friend/MemberFriendRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/service/command/FriendCommandService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/GroupRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/command/GroupCommandService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/query/GroupQueryService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberNotificationSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/NotificationStatus.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/facade/MemberFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member_group/repository/group_invite_repository/GroupInviteRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member_group/repository/member_group_repository/MemberGroupRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/api/NotificationApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/api/NotificationApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/data/dto/MemberNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/data/response/MemberNotificationResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/data/response/MemberNotificationSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/CategoryName.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/Notification.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/NotificationCategory.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/entity/NotificationStatus.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/repository/NotificationQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/repository/NotificationQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/repository/NotificationRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/service/NotificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/CreatedCapsuleSkinNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/FriendAcceptNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/FriendReqNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/FriendsReqNotificationsDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/GroupAcceptNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/GroupInviteNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/NotificationRequestMessage.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/TreasureCaptureNotificationDto.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/NotificationCategoryFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/NotificationFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenQueryRepositoryImplTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/notification/NotificationQueryRepositoryTest.java
Labels: feat

#530 fix : 알림 도메인 url 오류 수정 #529
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/api/AuthApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/api/NotificationApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/notification/api/NotificationApiController.java
Labels: fix

#537 fix : 블랙리스트 토큰 접근 오류 수정 #536
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/repository/BlackListCacheRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/jwt/JwtAuthenticationProvider.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/config/TestMockMvcSecurityConfig.java
  backend/core/src/test/java/site/timecapsulearchive/core/global/security/jwt/JwtAuthenticationProviderTest.java
Labels: fix, api fix

#545 feat : 전화번호 업데이트를 위한 인증 문자 전송, 인증 API 추가 #532
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/repository/MessageAuthenticationCacheRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/reqeust/PhoneVerificationMessageRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/facade/MemberFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
Labels: feat

#540 fix : 회원 탈퇴 후 일정 시간 내에 재가입 방지를 위한 상태 값 추가 #539
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberStatusDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberStatusResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
Labels: fix

#541 refact : MessageVerification 책임 분리 #532
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/repository/MessageAuthenticationCacheRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/service/AuthManager.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/reqeust/PhoneVerificationMessageRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/facade/MemberFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
Labels: refact

#542 fix : 보물 캡슐 중복 수령 시 필터링 #534
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/treasure_capsule/api/TreasureCapsuleController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/treasure_capsule/data/dto/TreasureCapsuleOpenDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/treasure_capsule/data/dto/TreasureOpenStatus.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/treasure_capsule/data/response/TreasureCapsuleOpenResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/treasure_capsule/service/TreasureCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/service/CapsuleSkinService.java
Labels: fix

#543 feat : 태그, 주소록 검색 허용 상태 및 변경 API 추가 #535
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/member_friend/MemberFriendQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/reqeust/UpdateMemberPhoneSearchAvailableRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/reqeust/UpdateMemberTagSearchAvailableRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/MemberTemporary.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/resources/db/migration/V31__tag_phone_search_avaiable.sql
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/member_friend/MemberFriendQueryRepositoryTest.java
Labels: feat

#544 feat : 사용자가 속한 그룹의 그룹 캡슐 목록 조회 API 추가 #533
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/dto/GroupCapsuleDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/dto/GroupSpecificCapsuleSliceRequestDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/GroupCapsuleResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/GroupCapsuleSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/GroupSpecificCapsuleSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member_group/repository/member_group_repository/MemberGroupQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member_group/repository/member_group_repository/MemberGroupQueryRepositoryImpl.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleServiceTest.java
Labels: feat

#553 feat : 공개, 그룹 캡슐 , 사용자 신고 기능 구현
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/Capsule.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/CapsuleType.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/capsule/CapsuleRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/resources/db/migration/V31__add_declaration_count_column.sql
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/GenericCapsuleServiceTest.java
Labels: feat

#554 fix : 기존 유저정보 조회 API 수정
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
Labels: api fix

#555 fix : 데이터베이스 유니크 중복 예외 처리
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/exception/MemberTagDuplicatedException.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/ErrorCode.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationServiceTest.java
Labels: fix

#557 feat : 캡슐 삭제 기능 구현
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/Capsule.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/CapsuleType.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/capsule/CapsuleRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/image/ImageRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/video/VideoRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/GroupCapsuleResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member_group/entity/MemberGroup.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/dependency/UnitTestDependency.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/dto/CapsuleDtoFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/dto/GroupCapsuleMemberDtoFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/GenericCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/media/repository/MediaQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/public_capsule/repository/PublicCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/public_capsule/service/PublicCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/service/command/FriendCommandServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/global/security/jwt/JwtAuthenticationProviderTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/global/security/jwt/JwtFactoryTest.java
Labels: feat

#569 feat : 캡슐 스킨 삭제 API 추가 #568
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/api/CapsuleSkinApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/api/CapsuleSkinApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/data/dto/CapsuleSkinDeleteResult.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/data/dto/CapsuleSkinDeleteResultDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/data/response/CapsuleSkinDeleteResultResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/entity/CapsuleSkin.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/repository/CapsuleSkinRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/service/CapsuleSkinService.java
Labels: feat

#573 build : 테스트 환경 ci-cd 환경 변수 수정
  .github/workflows/core-application-test-ci-cd-flow.yml
  .github/workflows/notification-application-test-ci-cd-flow.yml
Labels: build

#577 fix : 회원 상세 조회 API 응답 수정 #575
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
Labels: api fix

#596 fix : rabbitmq ssl 설정 추가 #595
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqProperties.java
  backend/core/src/main/resources/logback-spring.xml
Labels: fix

#588 build : core ci/cd prod 추가 #582
  .github/workflows/core-application-prod-ci-cd-flow.yml
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqProperties.java
  backend/core/src/main/resources/logback-spring.xml
Labels: build

#594 fix : file logging 방식 변경
  .github/workflows/animation-application-prod-ci-cd-flow.yml
  backend/AnimatedDrawings/Dockerfile
  backend/AnimatedDrawings/application/logging/logger_factory.py
  backend/AnimatedDrawings/application/task/base_task.py
  backend/AnimatedDrawings/supervisord.conf
Labels: fix
