Repository tukcomCD2024/DroidBlossom, pull requests merged in 2024-05, with the labels that each got.

#387 fix : 회원가입 시 임시 테이블 저장 후 기존 테이블로 변경
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/api/AuthApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/data/request/SignUpRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/SignUpRequestDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/MemberTemporary.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberTemporaryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/GlobalExceptionHandler.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/exception/NullCheckValidateException.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/util/NullCheck.java
  backend/core/src/main/resources/db/migration/V23__member_temporary_tabale_create.sql
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
Labels: api fix

#392 feat : AR, 지도용 내 주변에서 친구 캡슐 조회 #388
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/NearbyARCapsuleSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/NearbyARCapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/NearbyCapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/ErrorResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/GlobalExceptionHandler.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepositoryTest.java
Labels: feat

#393 feat : 마이페이지 타입별 캡슐 조회 #311
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/dto/MyGroupCapsuleDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/MyGroupCapsuleResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/MyGroupCapsuleSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/dto/MyPublicCapsuleDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/dto/MyPublicCapsuleSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/MyPublicCapsuleResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/repository/PublicCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/service/PublicCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApiController.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/GroupFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/MemberGroupFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/CapsuleFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepositoryTest.java
Labels: feat, fix

#357 feat : 그룹 캡슐 상세 & 요약 조회
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/GroupCapsuleOpen.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/CapsuleDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/CapsuleSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/CapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/CapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/dto/GroupCapsuleCreateRequestDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/dto/GroupCapsuleDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/dto/GroupCapsuleSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/reqeust/GroupCapsuleCreateRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/GroupCapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/data/response/GroupCapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/facade/GroupCapsuleFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleOpenService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/repository/PublicCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/service/PublicCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/repository/SecretCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupMemberSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqComponentConstants.java
  backend/core/src/main/resources/db/migration/V23__group_capsule_open_update.sql
  backend/core/src/main/resources/db/migration/V24__member_temporary_tabale_create.sql
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/GroupCapsuleOpenFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/dto/CapsuleDtoFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/GroupCapsuleOpenQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/GroupCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/service/GroupCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/service/PublicCapsuleServiceTest.java
Labels: feat

#395 fix : 브랜치 병합 오류 수정 #394
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/GroupFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/MemberGroupFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepositoryTest.java
Labels: fix

#396 feat : 그룹 목록, 상세 조회 추가 #360
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/CapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/CapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/NearbyARCapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/dto/PublicCapsuleDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/data/dto/MySecreteCapsuleDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/data/response/MySecreteCapsuleResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/data/response/CapsuleSkinSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/response/FriendSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/api/GroupApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/api/GroupApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupMemberDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/response/GroupDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/response/GroupMemberResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/response/GroupSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/response/GroupsPageResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/response/GroupsSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/GroupQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/GroupService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberNotificationResponse.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/RepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/GroupFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/MemberGroupFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/group/repository/MemberGroupQueryRepositoryTest.java
Labels: feat

#399 fix : dto to response 에러 수정
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/CapsuleSummaryDto.java
Labels: api fix

#401 Fix/update group capsule b #400
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/GroupQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/s3/manager/S3PreSignedUrlManager.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/MemberGroupFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/public_capsule/repository/PublicCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/public_capsule/service/PublicCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/GroupCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/group/repository/MemberGroupQueryRepositoryTest.java
Labels: api fix

#410 fix : AR용 주변 캡슐 조회 시 친구 캡슐만 조회되는 버그 #409
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepository.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepositoryTest.java
Labels: fix, api fix

#422 feat: 그룹 수락 기능 구현
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/NearbyARCapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/data/dto/MySecreteCapsuleDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/response/FriendReqStatusResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/FriendInviteRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/service/FriendService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/api/GroupApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/api/GroupApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupOwnerSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/entity/GroupInvite.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/entity/MemberGroup.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/exception/GroupInviteNotFoundException.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/exception/GroupOwnerAuthenticateException.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/GroupInviteRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/MemberGroupRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/groupInviteRepository/GroupInviteQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/groupInviteRepository/GroupInviteQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/groupInviteRepository/GroupInviteRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/groupRepository/GroupQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/groupRepository/GroupQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/groupRepository/GroupRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/memberGroupRepository/MemberGroupQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/memberGroupRepository/MemberGroupQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/memberGroupRepository/MemberGroupRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/GroupService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/GroupServiceImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/read/GroupReadService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/read/GroupReadServiceImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/write/GroupWriteService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/write/GroupWriteServiceImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitFailedComponentConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqComponentConstants.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/ErrorCode.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/GroupAcceptNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/data/dto/NotificationRequestMessage.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/queue/manager/SocialNotificationManager.java
  backend/core/src/main/resources/db/migration/V25__group_invite_update.sql
  backend/core/src/main/resources/db/migration/V26__group_invite_add.sql
  backend/core/src/test/java/site/timecapsulearchive/core/common/dependency/TestTransactionTemplate.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/dto/GroupDtoFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/group/repository/MemberGroupQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/group/service/GroupWriteServiceTest.java
Labels: feat

#423 feat : 그룹 수락 알림 기능 구현
  backend/notification/build.gradle
  backend/notification/src/main/java/site/timecapsulearchive/notification/data/dto/GroupAcceptNotificationDto.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/data/dto/GroupInviteNotificationDto.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/entity/CategoryName.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/global/config/RabbitmqComponentConstants.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/global/config/RabbitmqConfig.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/global/config/RabbitmqFailComponentConfig.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/global/config/RabbitmqProperties.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/global/error/GlobalExceptionHandler.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/exception/MessageNotSendAbleException.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/FCMManager.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/FcmMessageData.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/capsuleskin/CapsuleSkinFcmManager.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/capsuleskin/CapsuleSkinFcmManagerImpl.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/friend/FriendFcmManager.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/friend/FriendFcmManagerImpl.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/group/GroupFcmManager.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/infra/fcm/group/GroupFcmManagerImpl.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/repository/notification/NotificationQueryRepositoryImpl.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/repository/notification/NotificationRepository.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/service/capsuleskin/CapsuleSkinAlarmService.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/service/friend/FriendAlarmService.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/service/group/GroupAlarmListener.java
  backend/notification/src/main/java/site/timecapsulearchive/notification/service/group/GroupAlarmService.java
  backend/notification/src/main/resources/data.sql
Labels: feat

#415 feat : 그룹 캡슐 개봉 기능 추가
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/GroupCapsuleOpen.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/exception/GroupCapsuleOpenNotFoundException.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/repository/GroupCapsuleOpenRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/ErrorCode.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/domain/GroupCapsuleOpenFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/GroupCapsuleOpenQueryRepositoryTest.java
Labels: feat

#451 feat : 보물 타입 추가 및 기존 API 검증
  .gitignore
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/entity/CapsuleType.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepository.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepositoryTest.java
Labels: feat

#454 feat : 친구 태그 검색 개선
  backend/core/build.gradle
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/service/MessageVerificationService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/query/FriendQueryApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/query/FriendQueryApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/member_friend/MemberFriendQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/service/query/FriendQueryService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/SignUpRequestDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/MemberTemporary.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/repository/JpaAuditingConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/repository/MySQLFunctionContributor.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/repository/QueryDSLConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/repository/TransactionTemplateConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/oauth/service/CustomOAuth2UserService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/util/TagGenerator.java
  backend/core/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  backend/core/src/main/resources/db/migration/V28__member_tag_fulltext_index.sql
  backend/core/src/test/java/site/timecapsulearchive/core/common/RepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/service/FriendQueryServiceTest.java
Labels: fix

#456 performance : 그룹 상세조회 쿼리 개선
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupDetailTotalDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/GroupQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/GroupQueryRepositoryImpl.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/query/GroupQueryService.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/group/repository/GroupQueryRepositoryImplTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member_group/repository/MemberGroupQueryRepositoryTest.java
Labels: performance
