Repository tukcomCD2024/DroidBlossom, pull requests merged in 2024-01, with the labels that each got.

#6 style : 텍스트 크기 변경 및 style 추가
  frontend/ARchive/app/src/main/res/values/dimen.xml
  frontend/ARchive/app/src/main/res/values/style.xml
Labels: style

#23 feat : jwt 인증 기능 구현 #12
  backend/core/src/main/java/site/timecapsulearchive/core/CoreApplication.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/common/response/ErrorCode.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/common/response/ErrorResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/security/JwtDsl.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/security/JwtProperties.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/security/SecurityConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/exception/BusinessException.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/exception/InvalidTokenException.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/jwt/JwtAuthenticationFailureHandler.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/jwt/JwtAuthenticationFilter.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/jwt/JwtAuthenticationProvider.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/jwt/JwtAuthenticationToken.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/jwt/JwtConstants.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/security/jwt/JwtFactory.java
Labels: feat

#38 feat: 앱을 통한 로그인 #37
  backend/core/build.gradle
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/api/AuthApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/api/AuthApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/dto/request/CheckStatusRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/dto/request/SignUpRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/dto/request/TokenReIssueRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/dto/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/dto/response/MemberStatusResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/QueryDSLConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/SwaggerConfig.java
  backend/core/src/main/resources/db/migration/V1__init.sql
  backend/core/src/main/resources/db/migration/V2__member_update.sql
  backend/core/src/main/resources/db/migration/V3__member_update.sql
Labels: feat

#49 fix: swagger 문서화 수정
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/api/AuthApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/auth/dto/response/VerificationMessageSendResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
Labels: fix, docs

#56 build: github actions #28
  .github/workflows/ci-cd-flow.yml
  .github/workflows/google-java-format.yml
  backend/core/Dockerfile
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/ErrorResponse.java
Labels: build

#59 fix: member 엔드포인트 수정, health 추가 #58
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Member.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/api/ApiHealthCheckController.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/SwaggerConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/security/SecurityConfig.java
Labels: fix

#76 docs : README 수정
  README.md
Labels: docs

#83 refact/data store migration f #77
  frontend/ARchive/app/build.gradle
  frontend/ARchive/app/src/main/AndroidManifest.xml
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/ARchiveApplication.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/di/LocalModule.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/di/RetrofitModule.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/auth/AuthViewModelImpl.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/splash/SplashActivity.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/AccessTokenInterceptor.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/DataStoreUtils.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/EncryptionUtils.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/TokenAuthenticator.kt
Labels: refact

#84 fix : api 통신 중 Success , Fail , Exception & Success , Error 케이스 구분
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/common/FileNameDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/request/SecretCapsuleCreateRequestDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/request/SecretCapsulePageRequestDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/response/SecretCapsuleCreateResponseDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/response/SecretCapsulePageResponseDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/response/SecretCapsuleSummeryDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/common/FileName.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/secret/SecretCapsuleCreateRequest.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/secret/SecretCapsulePage.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/secret/SecretCapsulePageRequest.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/secret/SecretCapsuleSummery.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/auth/ReIssueUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/auth/SendMessageUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/auth/SignInUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/auth/SignUpUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/auth/TemporaryTokenReIssueUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/auth/TestUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/auth/ValidMessageUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/member/MemberStatusUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/member/MemberUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/auth/AuthViewModelImpl.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/home/HomeViewModelImpl.kt
Labels: fix

#85 Feat/capsule create api f #80
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/s3/request/S3UrlRequestDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/s3/response/S3UrlResponseDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/request/SecretCapsuleModifyRequestDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/response/SecretCapsuleDetailResponseDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/secret/response/SecretCapsuleModifyResponseDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/repository/S3RepositoryImpl.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/repository/SecretRepositoryImpl.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/source/remote/api/S3Service.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/source/remote/api/SecretService.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/di/RepositoryModule.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/di/RetrofitModule.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/di/ServiceModule.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/s3/S3UrlRequest.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/s3/S3Urls.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/secret/SecretCapsuleDetail.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/secret/SecretCapsuleModify.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/repository/S3Repository.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/repository/SecretRepository.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/s3/S3UrlsGetUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/secret/SecretCapsuleCreateUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/secret/SecretCapsuleDetailUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/secret/SecretCapsuleModifyUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/secret/SecretCapsulePageUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/DataStoreUtils.kt
Labels: feat
