Repository tukcomCD2024/DroidBlossom, pull requests merged in 2024-03, with the labels that each got.

#225 fix : 애니메이션 서버에서 알림 서버로 요청 스펙 수정
  backend/AnimatedDrawings/application/animation_queue.py
  backend/AnimatedDrawings/application/model/capsule_skin_creation_status.py
  backend/AnimatedDrawings/application/model/failed_task.py
  backend/AnimatedDrawings/application/task/base_task.py
  backend/AnimatedDrawings/application/task/send_notification.py
Labels: fix

#238 fix : 알림 서버 수정에 따른 API 요청 변경
  backend/AnimatedDrawings/application/model/capsule_skin_creation_status.py
  backend/AnimatedDrawings/application/model/notification_status.py
  backend/AnimatedDrawings/application/task/base_task.py
  backend/AnimatedDrawings/application/task/send_notification.py
Labels: fix

#240 fix : 트랜잭션 수정
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/service/CapsuleSkinService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/GlobalExceptionHandler.java
Labels: fix

#252 feat : fcm(SkinMake) - front
  frontend/ARchive/.gitignore
  frontend/ARchive/app/build.gradle
  frontend/ARchive/app/src/main/AndroidManifest.xml
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/member/request/FcmTokenRequsetDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/member/request/NotificationEnabledRequestDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/member/response/NoficationListResponseDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/dto/member/response/NotificationResponseDto.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/repository/MemberRepositoryImpl.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/data/source/remote/api/MemberService.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/di/LocalModule.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/member/NotificationModel.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/model/member/NotificationPage.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/repository/MemberRepository.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/member/FcmTokenUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/member/GetNotificationsUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/domain/usecase/member/NotificationEnabledUseCase.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/base/BaseActivity.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/snack/CallSnackBar.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/MainActivity.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/auth/AuthViewModel.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/auth/AuthViewModelImpl.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/auth/CertificationFragment.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/auth/SignUpFragment.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/home/createcapsule/CreateCapsule2Fragment.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/home/createcapsule/CreateCapsule3Fragment.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/home/createcapsule/adapter/SkinRVA.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/skin/SkinFragment.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/skin/SkinViewModel.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/skin/SkinViewModelImpl.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/skin/skinmake/SkinMakeFragment.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/presentation/ui/splash/SplashActivity.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/DataStoreUtils.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/DateUtils.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/FileUtils.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/MyFirebaseMessagingService.kt
  frontend/ARchive/app/src/main/java/com/droidblossom/archive/util/S3Util.kt
  frontend/ARchive/app/src/main/res/drawable/ic_close_silver.xml
  frontend/ARchive/app/src/main/res/font/suit_bold.ttf
  frontend/ARchive/app/src/main/res/font/suit_medium.ttf
  frontend/ARchive/app/src/main/res/layout/activity_capsule_detail.xml
  frontend/ARchive/app/src/main/res/layout/activity_skin_make.xml
  frontend/ARchive/app/src/main/res/layout/fragment_certification.xml
  frontend/ARchive/app/src/main/res/layout/fragment_create_capsule1.xml
  frontend/ARchive/app/src/main/res/layout/fragment_create_capsule2.xml
  frontend/ARchive/app/src/main/res/layout/fragment_create_capsule3.xml
  frontend/ARchive/app/src/main/res/layout/fragment_date_picker_dialog.xml
  frontend/ARchive/app/src/main/res/layout/fragment_sign_up.xml
  frontend/ARchive/app/src/main/res/layout/fragment_sign_up_success.xml
  frontend/ARchive/app/src/main/res/layout/item_group.xml
  frontend/ARchive/app/src/main/res/layout/item_skin.xml
  frontend/ARchive/app/src/main/res/values/colors.xml
  frontend/ARchive/app/src/main/res/values/strings.xml
  frontend/ARchive/app/src/main/res/values/style.xml
Labels: feat

#257 docs : readme 이미지 교체
  README.md
Labels: docs

#278 feat : 주소록 기반 친구 목록 조회 추가
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/dto/SearchFriendSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/mapper/MemberFriendMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/reqeust/SearchFriendsRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/response/SearchFriendSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/response/SearchFriendsResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/service/FriendService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/common/valid/annotation/Phone.java
  backend/core/src/main/resources/db/migration/V18__member_friend_update.sql
  backend/core/src/test/java/site/timecapsulearchive/core/common/RepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/service/FriendServiceTest.java
Labels: feat

#284 fix : animation 생성 시 celery 커넥션 오류 수정
  backend/AnimatedDrawings/application/__init__.py
  backend/AnimatedDrawings/application/animation_queue.py
  backend/AnimatedDrawings/application/logging/logger_factory.py
  backend/AnimatedDrawings/application/task/base_task.py
  backend/AnimatedDrawings/application/task/make_animation.py
  backend/AnimatedDrawings/application/task/save_capsule_skin.py
  backend/AnimatedDrawings/application/task/send_notification.py
  backend/AnimatedDrawings/supervisord.conf
Labels: fix
