Repository tukcomCD2024/DroidBlossom, pull requests merged in 2024-04, with the labels that each got.

#300 fix : 알림 목록 조회 버그 수정
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberNotificationResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/CategoryName.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/Notification.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/entity/NotificationStatus.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/FriendInviteFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/MemberFriendFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/NotificationCategoryFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/NotificationFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/UnitTestDependency.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
Labels: fix

#305 feat : 친구 캡슐 생성 기능 구현
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/mapper/CapsuleMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/repository/ImageQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/repository/VideoQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/data/dto/CapsuleCreateRequestDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/data/reqeust/CapsuleCreateRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/service/SecretCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/CapsuleFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/CapsuleSkinFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/ImageFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/UnitTestDependency.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/VideoFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/media/repository/MediaQueryRepositoryTest.java
Labels: feat

#312 refact : request param 이름 공통화
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/api/CapsuleSkinApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
Labels: refact

#319 fix : 공개 캡슐 상세 및 요약 조회 내 캡슐 조회하도록 수정
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepository.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepositoryTest.java
Labels: feat

#325 fix : 전화번호 검증 조건 변경
  backend/core/src/main/java/site/timecapsulearchive/core/global/common/valid/PhoneValidator.java
Labels: fix

#326 fix : 캡슐 상세 정보 응답 스펙 변경
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/CapsuleDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/mapper/CapsuleMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/repository/CapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/data/response/CapsuleDetailResponse.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/DatabaseContainer.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/RepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/NotificationFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/media/repository/MediaQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/service/PublicCapsuleServiceTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
Labels: feat, fix

#313 feat : 친구가 생성한 공개 캡슐 목록 조회 기능 구현
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/mapper/CapsuleMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/reqeust/PublicCapsuleCreateRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsulePageResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsuleSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/data/response/CapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/service/PublicCapsuleService.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/CapsuleFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/CapsuleSkinFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/data/fixture/UnitTestDependency.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/CapsuleFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/ImageFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/UnitTestDependency.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/VideoFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/media/repository/MediaQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepositoryTest.java
Labels: feat

#315 feat : 그룹 생성 기능 구현
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/CoordinateRangeDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/service/CapsuleSkinMessageManager.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/service/CapsuleSkinService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/api/GroupApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/api/GroupApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupCreateDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/dto/GroupInviteMessageDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/mapper/GroupMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/data/reqeust/GroupCreateRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/entity/Group.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/entity/MemberGroup.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/exception/GroupCreateException.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/GroupRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/repository/MemberGroupRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/GroupInviteMessageManager.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/GroupService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/error/ErrorCode.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/s3/controller/S3Api.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/s3/controller/S3ApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/s3/data/request/ImageS3PreSignedUrlRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/s3/manager/S3PreSignedUrlManager.java
Labels: feat

#327 fix : 마이페이지 응답 스펙 변경
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/api/MemberApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/dto/MemberDetailResponseDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/mapper/MemberMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/data/response/MemberDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/member/service/MemberServiceTest.java
Labels: feat, fix

#334 fix : 친구 캡슐 상세 및 요약 조회 오류 수정 #318
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/CapsuleDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/CapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/CapsuleSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/PublicCapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/mapper/CapsuleMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/dto/PublicCapsuleDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/dto/PublicCapsuleSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsuleSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/service/PublicCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/service/SecretCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/common/response/ResponseMappingConstant.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/s3/manager/S3PreSignedUrlManager.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/service/PublicCapsuleServiceTest.java
Labels: fix

#339 fix : 친구 찾기 쿼리 오타 수정
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepository.java
  backend/core/src/main/resources/db/migration/V22__member_friend_update.sql
Labels: fix

#347 hotfix : 포트 번호 수정
  .github/workflows/notification-application-ci-cd-flow.yml
Labels: fix, build

#340 feat : 친구 리스트로 친구 요청 #330
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsuleskin/service/CapsuleSkinMessageManager.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/request/SearchFriendsRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/request/SendFriendRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/facade/FriendFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/FriendInviteQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/service/FriendService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/group/service/GroupInviteMessageManager.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/repository/MemberQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/member/service/MemberService.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/TransactionTemplateConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqComponentConstants.java
  backend/core/src/main/java/site/timecapsulearchive/core/global/config/rabbitmq/RabbitmqConfig.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/notification/data/dto/FriendRequestNotificationDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/infra/notification/manager/NotificationManager.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/FriendInviteQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/service/FriendServiceTest.java
Labels: feat

#352 fix : 내 주변 캡슐 조회 오류 수정 #351
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/NearbyCapsuleSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/NearbyCapsuleResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/response/NearbyCapsuleSummaryResponse.java
Labels: fix

#361 refact : 캡슐 디렉토리 구조 개선
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApi.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/api/CapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/dto/CapsuleCreateRequestDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/data/request/CapsuleCreateRequest.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/facade/CapsuleFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/CapsuleRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/ImageQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/ImageRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/VideoQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/repository/VideoRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/CapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/ImageService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/generic_capsule/service/VideoService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/api/GroupCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/facade/GroupCapsuleFacade.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/group_capsule/service/GroupCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/api/PublicCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/dto/PublicCapsuleDetailDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsuleDetailResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/data/response/PublicCapsuleSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/repository/PublicCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/public_capsule/service/PublicCapsuleService.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/api/SecretCapsuleApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/repository/SecretCapsuleQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/capsule/secret_capsule/service/SecretCapsuleService.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/media/repository/MediaQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/repository/PublicCapsuleQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/capsule/service/PublicCapsuleServiceTest.java
Labels: refact

#370 fix : 친구 요청 목록 요청 받은 목록만 보이도록 수정 #369
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/api/FriendApiController.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/dto/FriendSummaryDto.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/mapper/FriendMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/mapper/MemberFriendMapper.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/response/FriendRequestsSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/response/FriendSummaryResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/data/response/FriendsSliceResponse.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/entity/FriendInvite.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/entity/FriendStatus.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepository.java
  backend/core/src/main/java/site/timecapsulearchive/core/domain/friend/service/FriendService.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/FriendInviteFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/common/fixture/MemberFixture.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/repository/MemberFriendQueryRepositoryTest.java
  backend/core/src/test/java/site/timecapsulearchive/core/domain/friend/service/FriendServiceTest.java
Labels: fix

#368 fix : ci/cd 변경 및 pr 시 test 하도록 수정
  .github/workflows/animation-application-ci-cd-flow.yml
  .github/workflows/core-application-ci-cd-flow.yml
  .github/workflows/notification-application-ci-cd-flow.yml
Labels: fix
